### ISSUE TITLE
Cross-platform?

### ISSUE THREAD

**Issue by rikai** [gblosser42/Discord-Dice#1]
I'm not terribly familiar with node, but i see there is a Discord.exe...

Does this mean that this project is windows-only, or can i run this dice bot on a linux server?

**Comment by gblosser42** [comment]
it was actually developed using linux, the windows exe is only there for
ease of use.

On linux, you will need to install Node.js and then run the command "node
discorddice.js" from the discord dice folder. The first time you do so, you
will be prompted to enter your login credentials.

There is currently a stability bug with the die roller that I am trying to
track down which causes it to crash every few hours on average. It still
works, and a quick restart of the dice program will fix matters

This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
