### ISSUE TITLE
Login info?

### ISSUE THREAD

**Issue by rikai** [gblosser42/Discord-Dice#2]
You should probably remove your login info from the config.json? And change your password :P

**Comment by gblosser42** [comment]
Shit. I thought I had that set up in the .gitignore. Thank you for pointing
it out, changing that right away

This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rikai** [comment]
You also missed Discord-Dice/node_modules/discord.js/test/auth.json <_<

**Comment by gblosser42** [comment]
That... is not actually mine. I'll contact the people who made that node
module and let them know though

This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
